apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: Telco Edge
    version: v0.1.0
  name: edge
spec:
  components:
    - name: edge
      properties:
        image: ghcr.io/liamrandall/telco_edge:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
        - properties:
            target: httpserver-edge
          type: linkdef
      type: actor
    - name: httpserver-edge
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
