apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: Telco Tower
    version: v0.1.2-daemonscaler-eu-up
  name: tower
spec:
  components:
    - name: tower-de
      properties:
        image: ghcr.io/liamrandall/telco_tower_de:0.1.1
      traits:
        - properties:
            replicas: 1
            spread:
              - name: alltowers_de
                requirements:
                  country: de
                  type: tower
          type: daemonscaler
        - properties:
            target: httpserver-kk
          type: linkdef
      type: actor
    - name: tower-fr
      properties:
        image: ghcr.io/liamrandall/telco_tower_fr:0.1.1
      traits:
        - properties:
            replicas: 1
            spread:
              - name: alltowers_fr
                requirements:
                  country: fr
                  type: tower
          type: daemonscaler
        - properties:
            target: httpserver-ll
          type: linkdef
      type: actor
    - name: httpserver-kk
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
    - name: httpserver-ll
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
