apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: Telco Tower
    version: v0.1.2-daemonscaler-eue
  name: tower
spec:
  components:
    - name: tower-de
      properties:
        image: ghcr.io/liamrandall/telco_tower_de:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: alltowers_de
                requirements:
                  country: de
                  type: tower
          type: daemonscaler
        - properties:
            target: httpserver-ii
          type: linkdef
      type: actor
    - name: tower-fr
      properties:
        image: ghcr.io/liamrandall/telco_tower_fr:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: alltowers_fr
                requirements:
                  country: fr
                  type: tower
          type: daemonscaler
        - properties:
            target: httpserver-jj
          type: linkdef
      type: actor
    - name: httpserver-ii
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
    - name: httpserver-jj
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.6.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
