apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: Telco Tower
    version: v0.1.0
  name: tower
spec:
  components:
    - name: tower
      properties:
        image: ghcr.io/liamrandall/telco_tower:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
        - properties:
            target: httpserver-gg
          type: linkdef
      type: actor
    - name: httpserver-gg
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
