apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: Telco User Daemonscaler
    version: v0.1.1-daemonscaler
  name: user
spec:
  components:
    - name: user
      properties:
        image: ghcr.io/liamrandall/telco_user:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: alluser
                requirements:
                  type: user
          type: daemonscaler
        - properties:
            target: httpserver-user
          type: linkdef
      type: actor
    - name: httpserver-user
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
