apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  annotations:
    description: Telco core Daemonscaler
    version: v0.1.1-daemonscaler
  name: core
spec:
  components:
    - name: core
      properties:
        image: ghcr.io/liamrandall/telco_core:0.1.0
      traits:
        - properties:
            replicas: 1
            spread:
              - name: allcore
                requirements:
                  type: core
          type: daemonscaler
        - properties:
            target: httpserver-core
          type: linkdef
      type: actor
    - name: httpserver-core
      properties:
        contract: wasmcloud:httpserver
        image: cosmonic.azurecr.io/httpserver_wormhole:0.5.4
      traits:
        - properties:
            replicas: 1
            spread:
              - name: oncosmonic
                requirements:
                  cosmonic_managed: 'true'
          type: spreadscaler
      type: capability
